"""Last version

Revision ID: 8f99427989dc
Revises: cc31a2cdf840
Create Date: 2025-09-06 00:15:29.105572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f99427989dc"
down_revision: Union[str, Sequence[str], None] = "cc31a2cdf840"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "age")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
