"""Test revision

Revision ID: cc31a2cdf840
Revises: 57dcc9067ba1
Create Date: 2025-09-06 00:13:56.964270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc31a2cdf840"
down_revision: Union[str, Sequence[str], None] = "57dcc9067ba1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "age")
    # ### end Alembic commands ###
