"""Base version of Database

Revision ID: f7e4f6fad92c
Revises: 8ca8e44be584
Create Date: 2025-07-31 06:46:58.873544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7e4f6fad92c"
down_revision: Union[str, Sequence[str], None] = "8ca8e44be584"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "selery")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("selery", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
